version: '3.8'

services:
  app_fe:
    container_name: app_fe
    build: ./docker/web
    ports:
      - 3000:3000
    privileged: true
    volumes:
      - ./applications:/applications:cached
    tty: true
    stdin_open: true
    command: /bin/sh
